export const SCHEDULE_TASKS = '@@SCHEDULE_TASKS'
export const RUN_SCHEDULED_TASKS = '@@RUN_SCHEDULED_TASKS'
export const TASKS_RESOLVED = '@@TASKS_RESOLVED'
export const STANDALONE_INIT = '@@STANDALONE_INIT'
